diff -urN iSponsorBlock/Makefile iSponsorBlock+jailed/Makefile
--- iSponsorBlock/Makefile	2022-03-10 16:51:13.040045976 +0700
+++ iSponsorBlock+jailed/Makefile	2022-03-10 16:51:01.956934868 +0700
@@ -1,10 +1,7 @@
-#Only use if using Xcode 12+
-PREFIX=$(THEOS)/toolchain/Xcode.xctoolchain/usr/bin/
-
-export ARCHS = arm64 arm64e
-TARGET := iphone:clang:13.4
+ARCHS = arm64 arm64e
+TARGET = iphone:14.5:13.0
 INSTALL_TARGET_PROCESSES = YouTube
-
+FINALPACKAGE = 1
 
 include $(THEOS)/makefiles/common.mk
 
@@ -13,5 +10,6 @@
 iSponsorBlock_FILES = iSponsorBlock.xm $(wildcard *.m)
 iSponsorBlock_LIBRARIES = colorpicker
 iSponsorBlock_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
+iSponsorBlock_FRAMEWORKS = UIKit CoreGraphics AVFoundation CoreMedia QuartzCore
 
 include $(THEOS_MAKE_PATH)/tweak.mk
