--- iSponsorBlock/Makefile	2022-03-10 18:25:44.430757313 +0700
+++ iSponsorBlock+jailed/Makefile	2022-03-10 18:36:25.343848124 +0700
@@ -1,11 +1,7 @@
-#Only use if using Xcode 12+
-PREFIX=$(THEOS)/toolchain/Xcode.xctoolchain/usr/bin/
-
-export ARCHS = arm64 arm64e
-TARGET := iphone:clang:13.4
+ARCHS = arm64 arm64e
+TARGET := iphone:clang:14.5:13.0
 INSTALL_TARGET_PROCESSES = YouTube
 
-
 include $(THEOS)/makefiles/common.mk
 
 TWEAK_NAME = iSponsorBlock
@@ -13,5 +9,6 @@
 iSponsorBlock_FILES = iSponsorBlock.xm $(wildcard *.m)
 iSponsorBlock_LIBRARIES = colorpicker
 iSponsorBlock_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
+iSponsorBlock_FRAMEWORKS = UIKit CoreGraphics AVFoundation CoreMedia QuartzCore
 
 include $(THEOS_MAKE_PATH)/tweak.mk
