name: 'Build IPA'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Setup Theos
        uses: beerpiss/theos-action@v1
      - 
        name: Setup theos-jailed
        run: |
          git clone --depth 1 --recursive https://github.com/kabiroberai/theos-jailed ${{ github.workspace }}/theos-jailed
          pushd ${{ github.workspace }}/theos-jailed
          ./install
          popd
      - 
        name: Installing build dependencies
        run: |
          curl -L https://raw.githubusercontent.com/Muirey03/RemoteLog/master/RemoteLog.h -o $THEOS/include/RemoteLog.h
          python3 -m ensurepip
          python3 -m pip install -U gdown
      - 
        name: Getting decrypted YouTube IPA
        run: |
          gdown ${{ secrets.DECRYPTED_YOUTUBE_IPA }} -O YouTube.ipa
      -
        name: Setting up build environment
        run: |
          echo YOUTUBE_IPA_FULLPATH="$(cd "$(dirname "YouTube.ipa")"; pwd -P)/$(basename "YouTube.ipa")" >> $GITHUB_ENV
          echo TERM=xterm >> $GITHUB_ENV
          mkdir -p out/
          set -o pipefail
      -
        name: Patching 
        run: |
          gmake do-patch 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
      - 
        name: Build (release)
        run: |
          gmake clean 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
          gmake package FINALPACKAGE=1 YoutubeRebornPlus_IPA=$YOUTUBE_IPA_FULLPATH 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
          mv packages/YoutubeRebornPlus1.0.0+git*.ipa out/
      - 
        name: Build (debug)
        run: |
          gmake clean 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'

          mkdir -p .theos/packages
          echo $(( $GITHUB_RUN_NUMBER - 1 )) > .theos/packages/-
          
          gmake package DEBUG=1 FINALPACKAGE=0 YoutubeRebornPlus_IPA=$YOUTUBE_IPA_FULLPATH 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
          mv packages/YoutubeRebornPlus1.0.0-debug.*+git*.ipa out/
      -
        name: Upload artifacts (release)
        uses: actions/upload-artifact@v3
        with:
          name: RELEASE
          path: out/YoutubeRebornPlus1.0.0+git*.ipa
      - 
        name: Upload artifacts (debug)
        uses: actions/upload-artifact@v3
        with:
          name: DEBUG
          path: out/YoutubeRebornPlus1.0.0-debug.*+git*.ipa
